### ISSUE TITLE
Install complete gstreamer suite (prerequiste for performing PiP and arbitrary camera support)

### ISSUE THREAD

**Issue by careyer** [HD-Fpv/Open.HD_Image_Builder#22]
Hi,

discovered that certain gstreamer modules are currently not installed, e.g. `omxh264enc`. This for example is a gstreamer h264 encoder which makes use of the Raspberry hardware encoder ;-) Very handy and resource friendly for our application :-)

For later extensions it would be beneficial to preinstall the complete gstreamer suite with all its addons and filters. Back in the days when I experimented with EZ-WBC 1.6 i did that with the following commands:

```
## Resize tmp-partion so we do not run into problems during bigger installs
nano /etc/fstab 	#(for device /tmp (ramdisk), change size=100M, CRTL-X. save)
reboot

##Update packages 
apt-get update'  	#(do not!!! perform 'upgrade')

## Install complete gstreamer-suite
## First install dependency fuse since needed
mkdir /dev/fuse
chmod +x /dev/fuse
apt-get install fuse
apt-get install gstreamer1.0
```

Thank you very much!

**Comment by pilotnbr1** [comment]
You sure we don’t have omx? We have always had fuse and gst1.0 and plugins but in order to get audio working we added even more got support. This is currently the gst specific packages installed


DEBIAN_FRONTEND=noninteractive sudo apt-get -yq install gstreamer1.0-plugins-base 
DEBIAN_FRONTEND=noninteractive sudo apt-get -yq install gstreamer1.0-plugins-good 
DEBIAN_FRONTEND=noninteractive sudo apt-get -yq install gstreamer1.0-plugins-bad 
DEBIAN_FRONTEND=noninteractive sudo apt-get -yq install gstreamer1.0-plugins-ugly 
DEBIAN_FRONTEND=noninteractive sudo apt-get -yq install gstreamer1.0-libav 
DEBIAN_FRONTEND=noninteractive sudo apt-get -yq install gstreamer1.0-tools 
DEBIAN_FRONTEND=noninteractive sudo apt-get -yq install gstreamer1.0-x 
DEBIAN_FRONTEND=noninteractive sudo apt-get -yq install gstreamer1.0-alsa 
DEBIAN_FRONTEND=noninteractive sudo apt-get -yq install gstreamer1.0-gl 
DEBIAN_FRONTEND=noninteractive sudo apt-get -yq install gstreamer1.0-gtk3 
DEBIAN_FRONTEND=noninteractive sudo apt-get -yq install gstreamer1.0-qt5 
DEBIAN_FRONTEND=noninteractive sudo apt-get -yq install gstreamer1.0-pulseaudio

**Comment by careyer** [comment]
@pilotnbr1 : Yes.... Vitaliy shared this a few days ago: 
![grafik](https://user-images.githubusercontent.com/6156251/54020044-1b8e1000-418d-11e9-8cea-b968a79b684a.png)

Afaik the omxh264enc is still considered under development and is not part of the standard  good, bad and ugly plugins. At least not in the gstreamer 1.0 install. ( I think it is included from v1.2 onwards by default).  I am not sure in what package this omx stuff is hidden so I installed via `apt-get install gstreamer1.0` were gstreamer1.0 is basically not a package but a wildcard to install anything that is assosiated with the gstreamer 1.0 suite. ;-). This works just fine and we will never ever miss anything from the gstreamer suite again ;-)

**Comment by pilotnbr1** [comment]
Added that to the rest of the gstreamer install commands. To test build development branch from stage 3 forward

**Comment by careyer** [comment]
Thank you very much! So I need to build the dev branch in order to test, right?

**Comment by pilotnbr1** [comment]
> Thank you very much! So I need to build the dev branch in order to test, right?

Yep! Good luck!

**Comment by pilotnbr1** [comment]
For record keeping.. Last mod did not work.

Gst-omx needs to be cloned from here
https://gitlab.freedesktop.org/gstreamer/gst-omx

Instructions lacking. Does have a build type of file and a makefile... need some investigating/instructions on how it’s compiled once cloned

**Comment by pilotnbr1** [comment]
Compiling OMX from scratch is a pain and poorly documented.

After looking for different precompiled sources came across this post with a patched version
https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=200306&sid=ea2a6bc57e0d534ff5956b8cce0cce3f&start=50

Attempting to build with package gstreamer1.0-omx-rpi-config

**Comment by careyer** [comment]
Problem has been solved thanks to @pilotnbr1 :-)
The omx modules are included in the dev branch now!
